site_name: SuperHexagon PPO
theme:
  logo: assets/icon.svg
  favicon: assets/icon.svg
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.instant
    - navigation.expand
    - toc.integrate
    - content.code.copy
    - content.code.annotate
    - search.suggest
    - search.highlight
    - navigation.indexes
  palette:
    - scheme: slate
      primary: blue
      accent: light blue
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
    - scheme: default
      primary: blue
      accent: light blue
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
  font:
    text: Roboto
    code: Fira Code
  icon:
    repo: fontawesome/brands/github

repo_url: https://github.com/Stinktopf/SuperHexagonAI
repo_name: Stinktopf/SuperHexagonAI

nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Architecture: architecture.md
  - Implementation: implementation.md
  - Performance: performance.md

plugins:
  - search:
      lang: en
  - mkdocstrings:
      handlers:
        python:
          options:
            show_root_heading: true
            show_source: true
            show_if_no_docstring: true

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.superfences
  - pymdownx.snippets
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.details
  - pymdownx.extra
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mermaid/10.0.0/mermaid.min.js

extra:
  social:
    - icon: fontawesome/solid/shield
      link: https://stinktopf.github.io/SuperHexagonAI/legal/
      name: Legal